module.exports = errorMessage = {
    USER_ALREADY_EXISTS: {
        "code": "USER_ALREADY_EXISTS",
        "message": "User already exists"
    },

    COMPANY_ALREADY_EXISTS: {
        "code": "COMPANY_ALREADY_EXISTS",
        "message": "Company already exists"
    },

    USER_ALLOCATION_ERROR:{
        "code": "USER_ALLOCATION_ERROR",
        "message": "User was not allocated to the company"
    },

    USER_NOT_FOUND:{
        "code":"USER_NOT_FOUND",
        "message":"User not found"
    },

    COMPANY_NOT_FOUND:{
        "code": "COMPANY_NOT_FOUND",
        "message": "Company not found"
    },

    INTERNAL_ERROR:{
        "code": "INTERNAL_ERROR",
        "message": "Internal error"
    }
}